// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-M1sCn0UHxYNsRthXuJqBPQkcXJyAGw',
    appId: '1:255936433981:web:80760d0f7751f97881bf54',
    messagingSenderId: '255936433981',
    projectId: 'ecommerceflutter-2026',
    authDomain: 'ecommerceflutter-2026.firebaseapp.com',
    storageBucket: 'ecommerceflutter-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3qrm2ZlFIf2DCgNDjRpJLx1n-NkU2ceI',
    appId: '1:255936433981:android:ed2b7649255939b981bf54',
    messagingSenderId: '255936433981',
    projectId: 'ecommerceflutter-2026',
    storageBucket: 'ecommerceflutter-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhuxwmGvG-7YjqqxdbQUdBcRJLBB5iuL0',
    appId: '1:255936433981:ios:527b6ac144a2b14581bf54',
    messagingSenderId: '255936433981',
    projectId: 'ecommerceflutter-2026',
    storageBucket: 'ecommerceflutter-2026.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhuxwmGvG-7YjqqxdbQUdBcRJLBB5iuL0',
    appId: '1:255936433981:ios:527b6ac144a2b14581bf54',
    messagingSenderId: '255936433981',
    projectId: 'ecommerceflutter-2026',
    storageBucket: 'ecommerceflutter-2026.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY-M1sCn0UHxYNsRthXuJqBPQkcXJyAGw',
    appId: '1:255936433981:web:2950de3680320bcd81bf54',
    messagingSenderId: '255936433981',
    projectId: 'ecommerceflutter-2026',
    authDomain: 'ecommerceflutter-2026.firebaseapp.com',
    storageBucket: 'ecommerceflutter-2026.firebasestorage.app',
  );
}
